version: '3.1'

services: 
  
  nginx:
    image: nginx:latest
    container_name: myapp_nginx
    ports:
        - 80:80
    volumes:
        - ./nginx:/etc/nginx/conf.d
        - ./logs/nginx:/var/log/nginx
        - .:/var/www
    environment:
      - NGINX_HOST=laravel5.com.test
      - NGINX_PORT=80
    # command: /bin/bash -c "envsubst < /etc/nginx/conf.d/laravel5.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    links:
        - php
    restart: on-failure
    # docker run --name some-wordpress --link=some-mysql:mysql -e WORDPRESS_DB_NAME=some_wordpress -v /var/docker/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini -v /var/docker/phpinfo.php:/var/www/html/phpinfo.php -p 8081:80  -d wordpress
  php:
    image: php:7.3-fpm
    container_name: myapp_php
    restart: on-failure
    ports:
      - 9000:9000
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./custom.ini:/usr/local/etc/php/conf.d/custom.ini

  mysql:
    image: mariadb:10.4.3
    container_name: myapp_mysql
    restart: on-failure
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: myapp-mydb
      MYSQL_ROOT_PASSWORD: Sawaddee1131
      MYSQL_USER: root
      MYSQL_PASSWORD: Sawaddee1131
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myapp_phpmyadmin
    environment:
      - PMA_HOST=myapp_mysql
      - PMA_ARBITRARY=1
      - PMA_USER=root
      - PMA_PASSWORD=Sawaddee1131
    restart: on-failure
    ports:
      - 8090:80
    volumes:
      - /sessions
    depends_on:
      - mysql
    
volumes:
  db_data: